services:
  - type: web
    name: todo-backend
    env: node
    rootDir: ./todo-multiuser-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production